<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_isToBeGiftWrapped</name>
   <tag></tag>
   <elementGuidId>727f4afb-81a0-4b9e-b99e-5879d46107e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sc-buy-box-gift-checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sc-buy-box-gift-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43132147-a837-4260-b03f-9b4a41722d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sc-buy-box-gift-checkbox</value>
      <webElementGuid>ae8c60b0-9dd0-4bfa-a752-695c1432bdf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9bb9ffcd-10f0-4dcd-948d-560bc54f5ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isToBeGiftWrapped</value>
      <webElementGuid>481a7819-8aca-4a85-acf1-653f4c3a3690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>91a3aabb-df48-4e6a-b80c-612fca4e6812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-buy-box-gift-checkbox&quot;)</value>
      <webElementGuid>30507673-2547-4828-9444-d3366a40bd49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sc-buy-box-gift-checkbox']</value>
      <webElementGuid>d763eddd-7097-4408-ab0b-fdf8162a5682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gutterCartViewForm']/div/div/div[2]/span/div/label/input</value>
      <webElementGuid>18e580d4-b6a6-471c-bb03-49937aeec0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>cfdc1c1f-42ee-41d1-8961-f881957f2288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sc-buy-box-gift-checkbox' and @type = 'checkbox' and @name = 'isToBeGiftWrapped']</value>
      <webElementGuid>063e095b-3c9a-4293-b76a-57aa225589a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
