<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_isToBeGiftWrapped</name>
   <tag></tag>
   <elementGuidId>efe4a57b-ec00-4130-afe4-aea8780850ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sc-buy-box-gift-checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sc-buy-box-gift-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78091434-ff62-4b6e-b489-1e208e2a73c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sc-buy-box-gift-checkbox</value>
      <webElementGuid>3ff5f444-f6df-4d9c-b01b-799af5c038bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e1bdb20b-2508-4e66-82fb-c261ad41b223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isToBeGiftWrapped</value>
      <webElementGuid>8503ab64-1a16-425b-9596-556e1c8d1e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d5b79e8b-05ac-4bcd-928d-5b06bc37b0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-buy-box-gift-checkbox&quot;)</value>
      <webElementGuid>721e70f6-a63f-4dd2-b908-3a354ecc240a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sc-buy-box-gift-checkbox']</value>
      <webElementGuid>10941d98-9bb1-45b3-9b8b-e294bc212bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gutterCartViewForm']/div/div/div[2]/span/div/label/input</value>
      <webElementGuid>0590737d-ef4b-4da5-8bca-eebd6c62410c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>292ed57e-ea66-4729-97ab-cafd5f77e917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sc-buy-box-gift-checkbox' and @type = 'checkbox' and @name = 'isToBeGiftWrapped']</value>
      <webElementGuid>41021fce-6792-4dde-86e6-4800187659dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
